name: 测试工作流  # 工作流的名称，会显示在 Actions 页面

# 触发条件：当代码推送到 main 分支，或有人提交 PR 到 main 分支时运行
on:
  push:
    branches: [ "main" ]  # 只监听 main 分支的 push 事件
  pull_request:
    branches: [ "main" ]  # 只监听针对 main 分支的 PR 事件

# 定义任务（Job）
jobs:
  test:  # 任务名称（可自定义）
    name: 运行测试  # 任务显示名称
    runs-on: ubuntu-latest  # 运行环境（使用最新版 Ubuntu 系统）
    
    # 任务中的步骤（Step）
    steps:
      - name: 拉取仓库代码  # 步骤1：获取当前仓库的代码
        uses: actions/checkout@v4  # 使用官方的 checkout Action，作用是拉取代码到运行环境
        
      - name: 安装 Node.js  # 步骤2：安装 Node.js（因为要运行 npm 命令）
        uses: actions/setup-node@v4  # 使用官方的 setup-node Action
        with:
          node-version: 20  # 指定 Node.js 版本为 20
          
      - name: 安装依赖  # 步骤3：安装项目依赖（如果是 Node.js 项目）
        run: npm install  # 运行终端命令（如果仓库没有 package.json，这一步会失败，后面会解决）
        
      - name: 运行测试  # 步骤4：执行测试命令
        run: npm test  # 运行测试（同样依赖 package.json 中的配置）
